# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QTabWidget, QWidget)
import flags_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(606, 396)
        MainWindow.setMinimumSize(QSize(606, 396))
        MainWindow.setMaximumSize(QSize(606, 396))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 601, 391))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.label = QLabel(self.tab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 10, 131, 91))
        self.label.setStyleSheet(u"image: url(:/flag/image/ir.png);")
        self.label_2 = QLabel(self.tab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 130, 131, 91))
        self.label_2.setStyleSheet(u"image: url(:/flag/image/de.png);")
        self.label_3 = QLabel(self.tab)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 250, 131, 91))
        self.label_3.setStyleSheet(u"image: url(:/flag/image/usa.png);")
        self.ir_time = QLabel(self.tab)
        self.ir_time.setObjectName(u"ir_time")
        self.ir_time.setGeometry(QRect(180, 30, 161, 41))
        font = QFont()
        font.setFamilies([u"Seven Segment"])
        font.setPointSize(28)
        self.ir_time.setFont(font)
        self.ir_time.setAlignment(Qt.AlignCenter)
        self.usa_time = QLabel(self.tab)
        self.usa_time.setObjectName(u"usa_time")
        self.usa_time.setGeometry(QRect(180, 150, 161, 41))
        self.usa_time.setFont(font)
        self.usa_time.setAlignment(Qt.AlignCenter)
        self.de_time = QLabel(self.tab)
        self.de_time.setObjectName(u"de_time")
        self.de_time.setGeometry(QRect(180, 270, 161, 41))
        self.de_time.setFont(font)
        self.de_time.setAlignment(Qt.AlignCenter)
        self.ir_timezone = QLabel(self.tab)
        self.ir_timezone.setObjectName(u"ir_timezone")
        self.ir_timezone.setGeometry(QRect(340, 30, 161, 41))
        font1 = QFont()
        font1.setFamilies([u"Seven Segment"])
        font1.setPointSize(20)
        self.ir_timezone.setFont(font1)
        self.ir_timezone.setStyleSheet(u"color: rgb(255, 0, 127);")
        self.ir_timezone.setAlignment(Qt.AlignCenter)
        self.de_timezone = QLabel(self.tab)
        self.de_timezone.setObjectName(u"de_timezone")
        self.de_timezone.setGeometry(QRect(340, 150, 161, 41))
        self.de_timezone.setFont(font1)
        self.de_timezone.setStyleSheet(u"color: rgb(255, 0, 127);")
        self.de_timezone.setAlignment(Qt.AlignCenter)
        self.us_timezone = QLabel(self.tab)
        self.us_timezone.setObjectName(u"us_timezone")
        self.us_timezone.setGeometry(QRect(340, 270, 161, 41))
        self.us_timezone.setFont(font1)
        self.us_timezone.setStyleSheet(u"color: rgb(255, 0, 127);")
        self.us_timezone.setAlignment(Qt.AlignCenter)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.btn_start_stopwatch = QPushButton(self.tab_3)
        self.btn_start_stopwatch.setObjectName(u"btn_start_stopwatch")
        self.btn_start_stopwatch.setGeometry(QRect(170, 170, 121, 61))
        font2 = QFont()
        font2.setPointSize(20)
        font2.setBold(True)
        self.btn_start_stopwatch.setFont(font2)
        self.btn_stop_stopwatch = QPushButton(self.tab_3)
        self.btn_stop_stopwatch.setObjectName(u"btn_stop_stopwatch")
        self.btn_stop_stopwatch.setGeometry(QRect(170, 240, 121, 61))
        self.btn_stop_stopwatch.setFont(font2)
        self.btn_reset_stopwatch = QPushButton(self.tab_3)
        self.btn_reset_stopwatch.setObjectName(u"btn_reset_stopwatch")
        self.btn_reset_stopwatch.setGeometry(QRect(300, 170, 121, 61))
        self.btn_reset_stopwatch.setFont(font2)
        self.lbl_stopwatch = QLabel(self.tab_3)
        self.lbl_stopwatch.setObjectName(u"lbl_stopwatch")
        self.lbl_stopwatch.setGeometry(QRect(230, 80, 121, 41))
        font3 = QFont()
        font3.setFamilies([u"Seven Segment"])
        font3.setPointSize(40)
        font3.setBold(True)
        self.lbl_stopwatch.setFont(font3)
        self.lbl_stopwatch.setAlignment(Qt.AlignCenter)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.btn_reset_timer = QPushButton(self.tab_4)
        self.btn_reset_timer.setObjectName(u"btn_reset_timer")
        self.btn_reset_timer.setGeometry(QRect(300, 180, 131, 61))
        self.btn_reset_timer.setFont(font2)
        self.btn_start_timer = QPushButton(self.tab_4)
        self.btn_start_timer.setObjectName(u"btn_start_timer")
        self.btn_start_timer.setGeometry(QRect(160, 180, 131, 61))
        self.btn_start_timer.setFont(font2)
        self.btn_stop_timer = QPushButton(self.tab_4)
        self.btn_stop_timer.setObjectName(u"btn_stop_timer")
        self.btn_stop_timer.setGeometry(QRect(160, 250, 131, 61))
        self.btn_stop_timer.setFont(font2)
        self.btn_stop_timer.setStyleSheet(u"")
        self.tb_minute_timer = QLineEdit(self.tab_4)
        self.tb_minute_timer.setObjectName(u"tb_minute_timer")
        self.tb_minute_timer.setGeometry(QRect(260, 90, 81, 71))
        font4 = QFont()
        font4.setFamilies([u"Seven Segment"])
        font4.setPointSize(40)
        self.tb_minute_timer.setFont(font4)
        self.tb_minute_timer.setStyleSheet(u"border:none;\n"
"background-color: rgb(240, 240, 240);\n"
"border-bottom:2px solid black;")
        self.tb_minute_timer.setAlignment(Qt.AlignCenter)
        self.tb_second_timer = QLineEdit(self.tab_4)
        self.tb_second_timer.setObjectName(u"tb_second_timer")
        self.tb_second_timer.setGeometry(QRect(360, 90, 81, 71))
        self.tb_second_timer.setFont(font4)
        self.tb_second_timer.setStyleSheet(u"border:none;\n"
"background-color: rgb(240, 240, 240);\n"
"border-bottom:2px solid black;")
        self.tb_second_timer.setAlignment(Qt.AlignCenter)
        self.tb_hour_timer = QLineEdit(self.tab_4)
        self.tb_hour_timer.setObjectName(u"tb_hour_timer")
        self.tb_hour_timer.setGeometry(QRect(160, 90, 81, 71))
        self.tb_hour_timer.setFont(font4)
        self.tb_hour_timer.setStyleSheet(u"border:none;\n"
"background-color: rgb(240, 240, 240);\n"
"border-bottom:2px solid black;")
        self.tb_hour_timer.setAlignment(Qt.AlignCenter)
        self.tb_hour_timer_2 = QLineEdit(self.tab_4)
        self.tb_hour_timer_2.setObjectName(u"tb_hour_timer_2")
        self.tb_hour_timer_2.setGeometry(QRect(230, 90, 31, 71))
        self.tb_hour_timer_2.setFont(font4)
        self.tb_hour_timer_2.setStyleSheet(u"border:none;\n"
"background-color: rgb(240, 240, 240);")
        self.tb_hour_timer_2.setAlignment(Qt.AlignCenter)
        self.tb_hour_timer_3 = QLineEdit(self.tab_4)
        self.tb_hour_timer_3.setObjectName(u"tb_hour_timer_3")
        self.tb_hour_timer_3.setGeometry(QRect(340, 90, 31, 71))
        self.tb_hour_timer_3.setFont(font4)
        self.tb_hour_timer_3.setStyleSheet(u"border:none;\n"
"background-color: rgb(240, 240, 240);")
        self.tb_hour_timer_3.setAlignment(Qt.AlignCenter)
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText("")
        self.label_2.setText("")
        self.label_3.setText("")
        self.ir_time.setText(QCoreApplication.translate("MainWindow", u"00:00:00", None))
        self.usa_time.setText(QCoreApplication.translate("MainWindow", u"00:00:00", None))
        self.de_time.setText(QCoreApplication.translate("MainWindow", u"00:00:00", None))
        self.ir_timezone.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.de_timezone.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.us_timezone.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"World Clock", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Alarm", None))
        self.btn_start_stopwatch.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.btn_stop_stopwatch.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.btn_reset_stopwatch.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.lbl_stopwatch.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Stop Watch", None))
        self.btn_reset_timer.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.btn_start_timer.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.btn_stop_timer.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.tb_minute_timer.setText(QCoreApplication.translate("MainWindow", u"15", None))
        self.tb_second_timer.setText(QCoreApplication.translate("MainWindow", u"30", None))
        self.tb_hour_timer.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.tb_hour_timer_2.setText(QCoreApplication.translate("MainWindow", u":", None))
        self.tb_hour_timer_3.setText(QCoreApplication.translate("MainWindow", u":", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"Timer", None))
    # retranslateUi

