# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QGridLayout,
    QHBoxLayout, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QSpinBox, QTabWidget,
    QVBoxLayout, QWidget)
import flag_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(606, 396)
        MainWindow.setMinimumSize(QSize(606, 396))
        MainWindow.setMaximumSize(QSize(606, 396))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 601, 391))
        font = QFont()
        font.setFamilies([u"IRANYekanX Bold"])
        font.setPointSize(16)
        font.setBold(True)
        self.tabWidget.setFont(font)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        font1 = QFont()
        font1.setPointSize(16)
        self.tab.setFont(font1)
        self.label = QLabel(self.tab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 10, 131, 91))
        self.label.setStyleSheet(u"image: url(:/flag/image/ir.png);")
        self.label_2 = QLabel(self.tab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 130, 131, 91))
        self.label_2.setStyleSheet(u"image: url(:/flag/image/de.png);")
        self.label_3 = QLabel(self.tab)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 250, 131, 91))
        self.label_3.setStyleSheet(u"image: url(:/flag/image/usa.png);")
        self.ir_time = QLabel(self.tab)
        self.ir_time.setObjectName(u"ir_time")
        self.ir_time.setGeometry(QRect(180, 30, 161, 41))
        font2 = QFont()
        font2.setFamilies([u"IRANYekanX Bold"])
        font2.setPointSize(28)
        font2.setBold(True)
        self.ir_time.setFont(font2)
        self.ir_time.setAlignment(Qt.AlignCenter)
        self.de_time = QLabel(self.tab)
        self.de_time.setObjectName(u"de_time")
        self.de_time.setGeometry(QRect(180, 150, 161, 41))
        self.de_time.setFont(font2)
        self.de_time.setAlignment(Qt.AlignCenter)
        self.us_time = QLabel(self.tab)
        self.us_time.setObjectName(u"us_time")
        self.us_time.setGeometry(QRect(180, 270, 161, 41))
        self.us_time.setFont(font2)
        self.us_time.setAlignment(Qt.AlignCenter)
        self.ir_timezone = QLabel(self.tab)
        self.ir_timezone.setObjectName(u"ir_timezone")
        self.ir_timezone.setGeometry(QRect(340, 30, 161, 41))
        font3 = QFont()
        font3.setFamilies([u"IRANYekanX Bold"])
        font3.setPointSize(20)
        font3.setBold(True)
        self.ir_timezone.setFont(font3)
        self.ir_timezone.setStyleSheet(u"color: rgb(255, 0, 127);")
        self.ir_timezone.setAlignment(Qt.AlignCenter)
        self.de_timezone = QLabel(self.tab)
        self.de_timezone.setObjectName(u"de_timezone")
        self.de_timezone.setGeometry(QRect(340, 150, 161, 41))
        self.de_timezone.setFont(font3)
        self.de_timezone.setStyleSheet(u"color: rgb(255, 0, 127);")
        self.de_timezone.setAlignment(Qt.AlignCenter)
        self.us_timezone = QLabel(self.tab)
        self.us_timezone.setObjectName(u"us_timezone")
        self.us_timezone.setGeometry(QRect(340, 270, 161, 41))
        self.us_timezone.setFont(font3)
        self.us_timezone.setStyleSheet(u"color: rgb(255, 0, 127);")
        self.us_timezone.setAlignment(Qt.AlignCenter)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.line_5 = QFrame(self.tab_2)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(320, -10, 20, 361))
        self.line_5.setFrameShape(QFrame.Shape.VLine)
        self.line_5.setFrameShadow(QFrame.Shadow.Sunken)
        self.edit_widget = QTabWidget(self.tab_2)
        self.edit_widget.setObjectName(u"edit_widget")
        self.edit_widget.setGeometry(QRect(350, 90, 231, 171))
        font4 = QFont()
        font4.setFamilies([u"IRANYekanX"])
        font4.setPointSize(10)
        font4.setBold(True)
        self.edit_widget.setFont(font4)
        self.edit_widget.setElideMode(Qt.ElideNone)
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.label_4 = QLabel(self.tab_6)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(0, 20, 81, 16))
        font5 = QFont()
        font5.setFamilies([u"IRANYekanX"])
        font5.setPointSize(12)
        font5.setBold(True)
        self.label_4.setFont(font5)
        self.label_5 = QLabel(self.tab_6)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(0, 60, 81, 16))
        self.label_5.setFont(font5)
        self.alarm_name = QLineEdit(self.tab_6)
        self.alarm_name.setObjectName(u"alarm_name")
        self.alarm_name.setEnabled(False)
        self.alarm_name.setGeometry(QRect(92, 20, 131, 20))
        self.alarm_name.setFont(font5)
        self.btn_edit_alarm = QPushButton(self.tab_6)
        self.btn_edit_alarm.setObjectName(u"btn_edit_alarm")
        self.btn_edit_alarm.setEnabled(False)
        self.btn_edit_alarm.setGeometry(QRect(4, 100, 221, 31))
        self.btn_edit_alarm.setFont(font4)
        self.alarm_hour_set = QSpinBox(self.tab_6)
        self.alarm_hour_set.setObjectName(u"alarm_hour_set")
        self.alarm_hour_set.setEnabled(False)
        self.alarm_hour_set.setGeometry(QRect(90, 60, 51, 31))
        self.alarm_hour_set.setMaximum(23)
        self.alarm_minute_set = QSpinBox(self.tab_6)
        self.alarm_minute_set.setObjectName(u"alarm_minute_set")
        self.alarm_minute_set.setEnabled(False)
        self.alarm_minute_set.setGeometry(QRect(160, 60, 51, 31))
        self.alarm_minute_set.setMaximum(59)
        self.label_6 = QLabel(self.tab_6)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(150, 66, 31, 16))
        self.label_6.setFont(font5)
        self.edit_widget.addTab(self.tab_6, "")
        self.gridLayoutWidget_2 = QWidget(self.tab_2)
        self.gridLayoutWidget_2.setObjectName(u"gridLayoutWidget_2")
        self.gridLayoutWidget_2.setGeometry(QRect(20, 0, 286, 347))
        self.gridLayoutWidget_2.setFont(font5)
        self.gridLayout_2 = QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.line_4 = QFrame(self.gridLayoutWidget_2)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setFrameShape(QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QFrame.Shadow.Sunken)

        self.verticalLayout.addWidget(self.line_4)

        self.alarm_time_1 = QLabel(self.gridLayoutWidget_2)
        self.alarm_time_1.setObjectName(u"alarm_time_1")
        font6 = QFont()
        font6.setFamilies([u"IRANYekanX"])
        font6.setPointSize(22)
        font6.setBold(True)
        self.alarm_time_1.setFont(font6)

        self.verticalLayout.addWidget(self.alarm_time_1)

        self.alarm_text_1 = QLabel(self.gridLayoutWidget_2)
        self.alarm_text_1.setObjectName(u"alarm_text_1")
        self.alarm_text_1.setFont(font5)
        self.alarm_text_1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.verticalLayout.addWidget(self.alarm_text_1)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.chk_active_1 = QCheckBox(self.gridLayoutWidget_2)
        self.chk_active_1.setObjectName(u"chk_active_1")
        self.chk_active_1.setFont(font4)

        self.horizontalLayout.addWidget(self.chk_active_1)

        self.btn_edit_1 = QPushButton(self.gridLayoutWidget_2)
        self.btn_edit_1.setObjectName(u"btn_edit_1")
        self.btn_edit_1.setFont(font4)

        self.horizontalLayout.addWidget(self.btn_edit_1)


        self.verticalLayout.addLayout(self.horizontalLayout)


        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.alarm_time_2 = QLabel(self.gridLayoutWidget_2)
        self.alarm_time_2.setObjectName(u"alarm_time_2")
        self.alarm_time_2.setFont(font6)

        self.verticalLayout_2.addWidget(self.alarm_time_2)

        self.alarm_text_2 = QLabel(self.gridLayoutWidget_2)
        self.alarm_text_2.setObjectName(u"alarm_text_2")
        self.alarm_text_2.setFont(font5)
        self.alarm_text_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.verticalLayout_2.addWidget(self.alarm_text_2)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.chk_active_2 = QCheckBox(self.gridLayoutWidget_2)
        self.chk_active_2.setObjectName(u"chk_active_2")
        self.chk_active_2.setFont(font4)

        self.horizontalLayout_2.addWidget(self.chk_active_2)

        self.btn_edit_2 = QPushButton(self.gridLayoutWidget_2)
        self.btn_edit_2.setObjectName(u"btn_edit_2")
        self.btn_edit_2.setFont(font4)

        self.horizontalLayout_2.addWidget(self.btn_edit_2)


        self.verticalLayout_2.addLayout(self.horizontalLayout_2)


        self.gridLayout_2.addLayout(self.verticalLayout_2, 2, 0, 1, 1)

        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.alarm_time_3 = QLabel(self.gridLayoutWidget_2)
        self.alarm_time_3.setObjectName(u"alarm_time_3")
        self.alarm_time_3.setFont(font6)

        self.verticalLayout_3.addWidget(self.alarm_time_3)

        self.alarm_text_3 = QLabel(self.gridLayoutWidget_2)
        self.alarm_text_3.setObjectName(u"alarm_text_3")
        self.alarm_text_3.setFont(font5)
        self.alarm_text_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.verticalLayout_3.addWidget(self.alarm_text_3)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.chk_active_3 = QCheckBox(self.gridLayoutWidget_2)
        self.chk_active_3.setObjectName(u"chk_active_3")
        self.chk_active_3.setFont(font4)

        self.horizontalLayout_3.addWidget(self.chk_active_3)

        self.btn_edit_3 = QPushButton(self.gridLayoutWidget_2)
        self.btn_edit_3.setObjectName(u"btn_edit_3")
        self.btn_edit_3.setFont(font4)

        self.horizontalLayout_3.addWidget(self.btn_edit_3)


        self.verticalLayout_3.addLayout(self.horizontalLayout_3)


        self.gridLayout_2.addLayout(self.verticalLayout_3, 4, 0, 1, 1)

        self.line = QFrame(self.gridLayoutWidget_2)
        self.line.setObjectName(u"line")
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)

        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 1)

        self.line_2 = QFrame(self.gridLayoutWidget_2)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)

        self.gridLayout_2.addWidget(self.line_2, 3, 0, 1, 1)

        self.line_3 = QFrame(self.gridLayoutWidget_2)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setFrameShape(QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)

        self.gridLayout_2.addWidget(self.line_3, 5, 0, 1, 1)

        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.btn_start_stopwatch = QPushButton(self.tab_3)
        self.btn_start_stopwatch.setObjectName(u"btn_start_stopwatch")
        self.btn_start_stopwatch.setGeometry(QRect(170, 170, 121, 61))
        self.btn_start_stopwatch.setFont(font3)
        self.btn_stop_stopwatch = QPushButton(self.tab_3)
        self.btn_stop_stopwatch.setObjectName(u"btn_stop_stopwatch")
        self.btn_stop_stopwatch.setGeometry(QRect(300, 170, 121, 61))
        self.btn_stop_stopwatch.setFont(font3)
        self.btn_reset_stopwatch = QPushButton(self.tab_3)
        self.btn_reset_stopwatch.setObjectName(u"btn_reset_stopwatch")
        self.btn_reset_stopwatch.setGeometry(QRect(170, 240, 251, 61))
        self.btn_reset_stopwatch.setFont(font3)
        self.lbl_stopwatch = QLabel(self.tab_3)
        self.lbl_stopwatch.setObjectName(u"lbl_stopwatch")
        self.lbl_stopwatch.setGeometry(QRect(170, 80, 251, 51))
        font7 = QFont()
        font7.setFamilies([u"Seven Segment"])
        font7.setPointSize(40)
        font7.setBold(True)
        self.lbl_stopwatch.setFont(font7)
        self.lbl_stopwatch.setAlignment(Qt.AlignCenter)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.btn_reset_timer = QPushButton(self.tab_4)
        self.btn_reset_timer.setObjectName(u"btn_reset_timer")
        self.btn_reset_timer.setGeometry(QRect(160, 250, 271, 61))
        self.btn_reset_timer.setFont(font3)
        self.btn_start_timer = QPushButton(self.tab_4)
        self.btn_start_timer.setObjectName(u"btn_start_timer")
        self.btn_start_timer.setGeometry(QRect(160, 180, 131, 61))
        self.btn_start_timer.setFont(font3)
        self.btn_stop_timer = QPushButton(self.tab_4)
        self.btn_stop_timer.setObjectName(u"btn_stop_timer")
        self.btn_stop_timer.setGeometry(QRect(300, 180, 131, 61))
        self.btn_stop_timer.setFont(font3)
        self.btn_stop_timer.setStyleSheet(u"")
        self.tb_minute_timer = QLineEdit(self.tab_4)
        self.tb_minute_timer.setObjectName(u"tb_minute_timer")
        self.tb_minute_timer.setGeometry(QRect(260, 90, 81, 71))
        font8 = QFont()
        font8.setFamilies([u"IRANYekanX Bold"])
        font8.setPointSize(40)
        font8.setBold(True)
        self.tb_minute_timer.setFont(font8)
        self.tb_minute_timer.setStyleSheet(u"border:none;\n"
"background-color: rgb(240, 240, 240);\n"
"border-bottom:2px solid black;")
        self.tb_minute_timer.setAlignment(Qt.AlignCenter)
        self.tb_second_timer = QLineEdit(self.tab_4)
        self.tb_second_timer.setObjectName(u"tb_second_timer")
        self.tb_second_timer.setGeometry(QRect(360, 90, 81, 71))
        self.tb_second_timer.setFont(font8)
        self.tb_second_timer.setStyleSheet(u"border:none;\n"
"background-color: rgb(240, 240, 240);\n"
"border-bottom:2px solid black;")
        self.tb_second_timer.setAlignment(Qt.AlignCenter)
        self.tb_hour_timer = QLineEdit(self.tab_4)
        self.tb_hour_timer.setObjectName(u"tb_hour_timer")
        self.tb_hour_timer.setGeometry(QRect(160, 90, 81, 71))
        self.tb_hour_timer.setFont(font8)
        self.tb_hour_timer.setStyleSheet(u"border:none;\n"
"background-color: rgb(240, 240, 240);\n"
"border-bottom:2px solid black;")
        self.tb_hour_timer.setAlignment(Qt.AlignCenter)
        self.tb_hour_timer_2 = QLineEdit(self.tab_4)
        self.tb_hour_timer_2.setObjectName(u"tb_hour_timer_2")
        self.tb_hour_timer_2.setGeometry(QRect(230, 90, 31, 71))
        self.tb_hour_timer_2.setFont(font8)
        self.tb_hour_timer_2.setStyleSheet(u"border:none;\n"
"background-color: rgb(240, 240, 240);")
        self.tb_hour_timer_2.setAlignment(Qt.AlignCenter)
        self.tb_hour_timer_2.setReadOnly(True)
        self.tb_hour_timer_3 = QLineEdit(self.tab_4)
        self.tb_hour_timer_3.setObjectName(u"tb_hour_timer_3")
        self.tb_hour_timer_3.setGeometry(QRect(340, 90, 31, 71))
        self.tb_hour_timer_3.setFont(font8)
        self.tb_hour_timer_3.setStyleSheet(u"border:none;\n"
"background-color: rgb(240, 240, 240);")
        self.tb_hour_timer_3.setAlignment(Qt.AlignCenter)
        self.tb_hour_timer_3.setReadOnly(True)
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText("")
        self.label_2.setText("")
        self.label_3.setText("")
        self.ir_time.setText(QCoreApplication.translate("MainWindow", u"00:00:00", None))
        self.de_time.setText(QCoreApplication.translate("MainWindow", u"00:00:00", None))
        self.us_time.setText(QCoreApplication.translate("MainWindow", u"00:00:00", None))
        self.ir_timezone.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.de_timezone.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.us_timezone.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"\u0633\u0627\u0639\u062a \u062c\u0647\u0627\u0646\u06cc", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u0646\u0627\u0645 \u0647\u0634\u062f\u0627\u0631", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u0632\u0645\u0627\u0646 \u0647\u0634\u062f\u0627\u0631", None))
        self.btn_edit_alarm.setText(QCoreApplication.translate("MainWindow", u"\u0648\u06cc\u0631\u0627\u06cc\u0634 \u0647\u0634\u062f\u0627\u0631", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u":", None))
        self.edit_widget.setTabText(self.edit_widget.indexOf(self.tab_6), QCoreApplication.translate("MainWindow", u"                               \u0648\u06cc\u0631\u0627\u06cc\u0634 \u0647\u0634\u062f\u0627\u0631                                ", None))
        self.alarm_time_1.setText(QCoreApplication.translate("MainWindow", u"00:00", None))
        self.alarm_text_1.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.chk_active_1.setText(QCoreApplication.translate("MainWindow", u"Active / Deactive", None))
        self.btn_edit_1.setText(QCoreApplication.translate("MainWindow", u"\u0648\u06cc\u0631\u0627\u06cc\u0634", None))
        self.alarm_time_2.setText(QCoreApplication.translate("MainWindow", u"00:00", None))
        self.alarm_text_2.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.chk_active_2.setText(QCoreApplication.translate("MainWindow", u"Active / Deactive", None))
        self.btn_edit_2.setText(QCoreApplication.translate("MainWindow", u"\u0648\u06cc\u0631\u0627\u06cc\u0634", None))
        self.alarm_time_3.setText(QCoreApplication.translate("MainWindow", u"00:00", None))
        self.alarm_text_3.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.chk_active_3.setText(QCoreApplication.translate("MainWindow", u"Active / Deactive", None))
        self.btn_edit_3.setText(QCoreApplication.translate("MainWindow", u"\u0648\u06cc\u0631\u0627\u06cc\u0634", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"\u0647\u0634\u062f\u0627\u0631", None))
        self.btn_start_stopwatch.setText(QCoreApplication.translate("MainWindow", u"\u0634\u0631\u0648\u0639", None))
        self.btn_stop_stopwatch.setText(QCoreApplication.translate("MainWindow", u"\u062a\u0648\u0642\u0641", None))
        self.btn_reset_stopwatch.setText(QCoreApplication.translate("MainWindow", u"\u0634\u0631\u0648\u0639 \u0645\u062c\u062f\u062f", None))
        self.lbl_stopwatch.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"\u06a9\u0631\u0646\u0648\u0645\u062a\u0631", None))
        self.btn_reset_timer.setText(QCoreApplication.translate("MainWindow", u"\u0634\u0631\u0648\u0639 \u0645\u062c\u062f\u062f", None))
        self.btn_start_timer.setText(QCoreApplication.translate("MainWindow", u"\u0634\u0631\u0648\u0639", None))
        self.btn_stop_timer.setText(QCoreApplication.translate("MainWindow", u"\u062a\u0648\u0642\u0641", None))
        self.tb_minute_timer.setText(QCoreApplication.translate("MainWindow", u"15", None))
        self.tb_second_timer.setText(QCoreApplication.translate("MainWindow", u"30", None))
        self.tb_hour_timer.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.tb_hour_timer_2.setText(QCoreApplication.translate("MainWindow", u":", None))
        self.tb_hour_timer_3.setText(QCoreApplication.translate("MainWindow", u":", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"\u062a\u0627\u06cc\u0645\u0631", None))
    # retranslateUi

