# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QHBoxLayout, QLabel, QLineEdit,
    QMainWindow, QPushButton, QSizePolicy, QTabWidget,
    QWidget)
import flags_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(606, 396)
        MainWindow.setMinimumSize(QSize(606, 396))
        MainWindow.setMaximumSize(QSize(606, 396))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 601, 391))
        font = QFont()
        font.setFamilies([u"IRANYekanX Bold"])
        font.setPointSize(16)
        font.setBold(True)
        self.tabWidget.setFont(font)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        font1 = QFont()
        font1.setPointSize(16)
        self.tab.setFont(font1)
        self.label = QLabel(self.tab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 10, 131, 91))
        self.label.setStyleSheet(u"image: url(:/flag/image/ir.png);")
        self.label_2 = QLabel(self.tab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 130, 131, 91))
        self.label_2.setStyleSheet(u"image: url(:/flag/image/de.png);")
        self.label_3 = QLabel(self.tab)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 250, 131, 91))
        self.label_3.setStyleSheet(u"image: url(:/flag/image/usa.png);")
        self.ir_time = QLabel(self.tab)
        self.ir_time.setObjectName(u"ir_time")
        self.ir_time.setGeometry(QRect(180, 30, 161, 41))
        font2 = QFont()
        font2.setFamilies([u"IRANYekanX Bold"])
        font2.setPointSize(28)
        font2.setBold(True)
        self.ir_time.setFont(font2)
        self.ir_time.setAlignment(Qt.AlignCenter)
        self.de_time = QLabel(self.tab)
        self.de_time.setObjectName(u"de_time")
        self.de_time.setGeometry(QRect(180, 150, 161, 41))
        self.de_time.setFont(font2)
        self.de_time.setAlignment(Qt.AlignCenter)
        self.us_time = QLabel(self.tab)
        self.us_time.setObjectName(u"us_time")
        self.us_time.setGeometry(QRect(180, 270, 161, 41))
        self.us_time.setFont(font2)
        self.us_time.setAlignment(Qt.AlignCenter)
        self.ir_timezone = QLabel(self.tab)
        self.ir_timezone.setObjectName(u"ir_timezone")
        self.ir_timezone.setGeometry(QRect(340, 30, 161, 41))
        font3 = QFont()
        font3.setFamilies([u"IRANYekanX Bold"])
        font3.setPointSize(20)
        font3.setBold(True)
        self.ir_timezone.setFont(font3)
        self.ir_timezone.setStyleSheet(u"color: rgb(255, 0, 127);")
        self.ir_timezone.setAlignment(Qt.AlignCenter)
        self.de_timezone = QLabel(self.tab)
        self.de_timezone.setObjectName(u"de_timezone")
        self.de_timezone.setGeometry(QRect(340, 150, 161, 41))
        self.de_timezone.setFont(font3)
        self.de_timezone.setStyleSheet(u"color: rgb(255, 0, 127);")
        self.de_timezone.setAlignment(Qt.AlignCenter)
        self.us_timezone = QLabel(self.tab)
        self.us_timezone.setObjectName(u"us_timezone")
        self.us_timezone.setGeometry(QRect(340, 270, 161, 41))
        self.us_timezone.setFont(font3)
        self.us_timezone.setStyleSheet(u"color: rgb(255, 0, 127);")
        self.us_timezone.setAlignment(Qt.AlignCenter)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.horizontalLayoutWidget = QWidget(self.tab_2)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(0, 300, 591, 58))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.add_alarm = QPushButton(self.horizontalLayoutWidget)
        self.add_alarm.setObjectName(u"add_alarm")
        font4 = QFont()
        font4.setPointSize(22)
        self.add_alarm.setFont(font4)

        self.horizontalLayout.addWidget(self.add_alarm)

        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.btn_start_stopwatch = QPushButton(self.tab_3)
        self.btn_start_stopwatch.setObjectName(u"btn_start_stopwatch")
        self.btn_start_stopwatch.setGeometry(QRect(170, 170, 121, 61))
        self.btn_start_stopwatch.setFont(font3)
        self.btn_stop_stopwatch = QPushButton(self.tab_3)
        self.btn_stop_stopwatch.setObjectName(u"btn_stop_stopwatch")
        self.btn_stop_stopwatch.setGeometry(QRect(300, 170, 121, 61))
        self.btn_stop_stopwatch.setFont(font3)
        self.btn_reset_stopwatch = QPushButton(self.tab_3)
        self.btn_reset_stopwatch.setObjectName(u"btn_reset_stopwatch")
        self.btn_reset_stopwatch.setGeometry(QRect(170, 240, 251, 61))
        self.btn_reset_stopwatch.setFont(font3)
        self.lbl_stopwatch = QLabel(self.tab_3)
        self.lbl_stopwatch.setObjectName(u"lbl_stopwatch")
        self.lbl_stopwatch.setGeometry(QRect(170, 80, 251, 51))
        font5 = QFont()
        font5.setFamilies([u"Seven Segment"])
        font5.setPointSize(40)
        font5.setBold(True)
        self.lbl_stopwatch.setFont(font5)
        self.lbl_stopwatch.setAlignment(Qt.AlignCenter)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.btn_reset_timer = QPushButton(self.tab_4)
        self.btn_reset_timer.setObjectName(u"btn_reset_timer")
        self.btn_reset_timer.setGeometry(QRect(160, 250, 271, 61))
        self.btn_reset_timer.setFont(font3)
        self.btn_start_timer = QPushButton(self.tab_4)
        self.btn_start_timer.setObjectName(u"btn_start_timer")
        self.btn_start_timer.setGeometry(QRect(160, 180, 131, 61))
        self.btn_start_timer.setFont(font3)
        self.btn_stop_timer = QPushButton(self.tab_4)
        self.btn_stop_timer.setObjectName(u"btn_stop_timer")
        self.btn_stop_timer.setGeometry(QRect(300, 180, 131, 61))
        self.btn_stop_timer.setFont(font3)
        self.btn_stop_timer.setStyleSheet(u"")
        self.tb_minute_timer = QLineEdit(self.tab_4)
        self.tb_minute_timer.setObjectName(u"tb_minute_timer")
        self.tb_minute_timer.setGeometry(QRect(260, 90, 81, 71))
        font6 = QFont()
        font6.setFamilies([u"IRANYekanX Bold"])
        font6.setPointSize(40)
        font6.setBold(True)
        self.tb_minute_timer.setFont(font6)
        self.tb_minute_timer.setStyleSheet(u"border:none;\n"
"background-color: rgb(240, 240, 240);\n"
"border-bottom:2px solid black;")
        self.tb_minute_timer.setAlignment(Qt.AlignCenter)
        self.tb_second_timer = QLineEdit(self.tab_4)
        self.tb_second_timer.setObjectName(u"tb_second_timer")
        self.tb_second_timer.setGeometry(QRect(360, 90, 81, 71))
        self.tb_second_timer.setFont(font6)
        self.tb_second_timer.setStyleSheet(u"border:none;\n"
"background-color: rgb(240, 240, 240);\n"
"border-bottom:2px solid black;")
        self.tb_second_timer.setAlignment(Qt.AlignCenter)
        self.tb_hour_timer = QLineEdit(self.tab_4)
        self.tb_hour_timer.setObjectName(u"tb_hour_timer")
        self.tb_hour_timer.setGeometry(QRect(160, 90, 81, 71))
        self.tb_hour_timer.setFont(font6)
        self.tb_hour_timer.setStyleSheet(u"border:none;\n"
"background-color: rgb(240, 240, 240);\n"
"border-bottom:2px solid black;")
        self.tb_hour_timer.setAlignment(Qt.AlignCenter)
        self.tb_hour_timer_2 = QLineEdit(self.tab_4)
        self.tb_hour_timer_2.setObjectName(u"tb_hour_timer_2")
        self.tb_hour_timer_2.setGeometry(QRect(230, 90, 31, 71))
        self.tb_hour_timer_2.setFont(font6)
        self.tb_hour_timer_2.setStyleSheet(u"border:none;\n"
"background-color: rgb(240, 240, 240);")
        self.tb_hour_timer_2.setAlignment(Qt.AlignCenter)
        self.tb_hour_timer_2.setReadOnly(True)
        self.tb_hour_timer_3 = QLineEdit(self.tab_4)
        self.tb_hour_timer_3.setObjectName(u"tb_hour_timer_3")
        self.tb_hour_timer_3.setGeometry(QRect(340, 90, 31, 71))
        self.tb_hour_timer_3.setFont(font6)
        self.tb_hour_timer_3.setStyleSheet(u"border:none;\n"
"background-color: rgb(240, 240, 240);")
        self.tb_hour_timer_3.setAlignment(Qt.AlignCenter)
        self.tb_hour_timer_3.setReadOnly(True)
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText("")
        self.label_2.setText("")
        self.label_3.setText("")
        self.ir_time.setText(QCoreApplication.translate("MainWindow", u"00:00:00", None))
        self.de_time.setText(QCoreApplication.translate("MainWindow", u"00:00:00", None))
        self.us_time.setText(QCoreApplication.translate("MainWindow", u"00:00:00", None))
        self.ir_timezone.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.de_timezone.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.us_timezone.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"\u0633\u0627\u0639\u062a \u062c\u0647\u0627\u0646\u06cc", None))
        self.add_alarm.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"\u0647\u0634\u062f\u0627\u0631", None))
        self.btn_start_stopwatch.setText(QCoreApplication.translate("MainWindow", u"\u0634\u0631\u0648\u0639", None))
        self.btn_stop_stopwatch.setText(QCoreApplication.translate("MainWindow", u"\u062a\u0648\u0642\u0641", None))
        self.btn_reset_stopwatch.setText(QCoreApplication.translate("MainWindow", u"\u0634\u0631\u0648\u0639 \u0645\u062c\u062f\u062f", None))
        self.lbl_stopwatch.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"\u06a9\u0631\u0646\u0648\u0645\u062a\u0631", None))
        self.btn_reset_timer.setText(QCoreApplication.translate("MainWindow", u"\u0634\u0631\u0648\u0639 \u0645\u062c\u062f\u062f", None))
        self.btn_start_timer.setText(QCoreApplication.translate("MainWindow", u"\u0634\u0631\u0648\u0639", None))
        self.btn_stop_timer.setText(QCoreApplication.translate("MainWindow", u"\u062a\u0648\u0642\u0641", None))
        self.tb_minute_timer.setText(QCoreApplication.translate("MainWindow", u"15", None))
        self.tb_second_timer.setText(QCoreApplication.translate("MainWindow", u"30", None))
        self.tb_hour_timer.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.tb_hour_timer_2.setText(QCoreApplication.translate("MainWindow", u":", None))
        self.tb_hour_timer_3.setText(QCoreApplication.translate("MainWindow", u":", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"\u062a\u0627\u06cc\u0645\u0631", None))
    # retranslateUi

